/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

import java.util.Scanner;

public class GameOfLife {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Board board = new Board();
        Scanner input = new Scanner(System.in);

        System.out.println("---------- Generation 0 ----------");
        board.printBoard(board.createBoard());
        System.out.println("Introduce generation numbers: ");
        int generationNumbers = input.nextInt();
        int counter = 0;

        while(counter <= generationNumbers) {
            System.out.println("---------- Generation " + (counter + 1) + " ----------");
            board.nextGeneration();
            board.printBoard(board.getBoard());
            counter++;
        }
    }
}
