/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

import org.junit.Test;
import static org.junit.Assert.*;

public class GameOfLifeTest {
    @Test public void appHasAGreeting() {
        GameOfLife classUnderTest = new GameOfLife();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
