/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Conway.game.of.life;

import java.util.Scanner;

public class GameOfLife {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Grid grid = new Grid();
        Scanner input = new Scanner(System.in);

        System.out.println("---------- Generation 0 ----------");
        grid.printBoard(grid.createBoard());
        System.out.println("Introduce generation numbers: ");
        int generationNumbers = input.nextInt();
        int counter = 0;

        while(counter <= generationNumbers) {
            System.out.println("---------- Generation " + (counter + 1) + " ----------");
            grid.nextGeneration();
            grid.printBoard(grid.getBoard());
            counter++;
        }
    }
}
